local M = {}
local p = require("kawaii-theme.palette")

M.config = {
  transparent = false,
}

function M.setup(opts)
  M.config = vim.tbl_deep_extend("force", M.config, opts or {})
  vim.g.kawaiitheme_transparent = M.config.transparent
end

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

local function link(group, target)
  hl(group, { link = target })
end

function M.load()
  vim.o.background = "dark"
  vim.cmd("highlight clear")

  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end

  vim.o.termguicolors = true
  vim.g.colors_name = "kawaii-theme"

  local bg = M.config.transparent and p.none or p.bg
  local bg_float = M.config.transparent and p.none or p.bg_float
  local bg_dark = M.config.transparent and p.none or p.bg_dark
  local eob_fg = M.config.transparent and p.bg or bg

  vim.g.kawaiitheme_palette = p

  -- Base UI
  hl("Normal", { fg = p.fg, bg = bg })
  hl("NormalNC", { fg = p.fg, bg = bg })
  hl("NormalFloat", { fg = p.fg, bg = bg_float })
  hl("FloatBorder", { fg = p.pink2, bg = bg_float })
  hl("FloatTitle", { fg = p.pink3, bg = bg_float, bold = true })
  hl("FloatFooter", { fg = p.fg_dark, bg = bg_float })
  hl("FloatShadow", { bg = bg_dark })
  hl("FloatShadowThrough", { bg = bg_dark })
  hl("SignColumn", { bg = bg })
  hl("LineNr", { fg = p.comment, bg = bg })
  hl("CursorLine", { bg = p.selection })
  hl("CursorColumn", { bg = bg_dark })
  hl("CursorLineNr", { fg = p.yellow, bg = bg, bold = true })
  hl("ColorColumn", { bg = bg_dark })
  hl("EndOfBuffer", { fg = eob_fg, bg = bg })
  hl("NonText", { fg = p.border })
  hl("Whitespace", { fg = p.border })
  hl("SpecialKey", { fg = p.comment })
  hl("Conceal", { fg = p.comment })
  hl("Directory", { fg = p.pink3, bold = true })
  hl("Visual", { bg = p.selection })
  hl("VisualNOS", { bg = p.selection })
  hl("Search", { fg = p.bg, bg = p.yellow })
  hl("IncSearch", { fg = p.bg, bg = p.pink3 })
  hl("CurSearch", { fg = p.bg, bg = p.pink3 })
  hl("MatchParen", { fg = p.yellow, bg = p.selection, bold = true })
  hl("Folded", { fg = p.muted, bg = bg_dark })
  hl("FoldColumn", { fg = p.comment, bg = bg })
  hl("QuickFixLine", { bg = p.selection, bold = true })
  hl("Substitute", { fg = p.bg, bg = p.pink3 })

  -- Status / tab
  hl("StatusLine", { fg = p.fg, bg = bg_dark })
  hl("StatusLineNC", { fg = p.muted, bg = bg })
  hl("WinSeparator", { fg = p.border })
  hl("TabLine", { fg = p.muted, bg = bg_dark })
  hl("TabLineSel", { fg = p.pink, bg = bg })
  hl("TabLineFill", { bg = bg })
  hl("WildMenu", { fg = p.bg, bg = p.yellow })
  hl("WinBar", { fg = p.fg, bg = bg_dark })
  hl("WinBarNC", { fg = p.muted, bg = bg_dark })
  hl("Title", { fg = p.pink3, bold = true })
  hl("Question", { fg = p.green })
  hl("MoreMsg", { fg = p.green })
  hl("OkMsg", { fg = p.green })
  hl("ModeMsg", { fg = p.yellow })
  hl("MsgSeparator", { bg = bg_dark })
  hl("ErrorMsg", { fg = p.red })
  hl("WarningMsg", { fg = p.yellow })
  hl("RedrawDebugNormal", { reverse = true })
  hl("RedrawDebugClear", { bg = p.yellow })
  hl("RedrawDebugComposed", { bg = p.green })
  hl("RedrawDebugRecompose", { bg = p.red })
  hl("NvimInternalError", { fg = p.red, bg = bg })

  -- Syntax
  hl("Comment", { fg = p.comment })
  hl("String", { fg = p.pink3 })
  hl("Number", { fg = p.pink })
  hl("Boolean", { fg = p.pink2, bold = true })
  hl("Constant", { fg = p.pink3 })
  hl("Function", { fg = p.yellow })
  hl("Keyword", { fg = p.pink4 })
  hl("Statement", { fg = p.pink4 })
  hl("Operator", { fg = p.pink4 })
  hl("PreProc", { fg = p.purple })
  hl("Type", { fg = p.pink4, italic = true })
  hl("Special", { fg = p.purple })
  hl("Delimiter", { fg = p.fg_dark })
  hl("Identifier", { fg = p.fg })
  hl("Todo", { fg = p.bg, bg = p.yellow, bold = true })
  hl("Error", { fg = p.red })

  -- Treesitter
  hl("@comment", { fg = p.comment })
  hl("@string", { fg = p.pink3 })
  hl("@number", { fg = p.pink })
  hl("@boolean", { fg = p.pink2, bold = true })
  hl("@constant", { fg = p.pink3 })
  hl("@constant.builtin", { fg = p.pink3 })
  hl("@variable", { fg = p.fg })
  hl("@variable.builtin", { fg = p.purple, italic = true })
  hl("@variable.member", { fg = p.purple })
  hl("@variable.parameter", { fg = p.yellow, italic = true })
  hl("@function", { fg = p.yellow })
  hl("@function.builtin", { fg = p.yellow })
  hl("@function.call", { fg = p.yellow })
  hl("@function.method", { fg = p.yellow })
  hl("@function.method.call", { fg = p.yellow })
  hl("@keyword", { fg = p.pink4 })
  hl("@keyword.function", { fg = p.pink4 })
  hl("@keyword.import", { fg = p.pink4 })
  hl("@keyword.operator", { fg = p.pink4 })
  hl("@keyword.return", { fg = p.pink4 })
  hl("@operator", { fg = p.pink4 })
  hl("@type", { fg = p.pink4, italic = true })
  hl("@type.builtin", { fg = p.pink4, italic = true })
  hl("@module", { fg = p.pink4, italic = true })
  hl("@constructor", { fg = p.purple })
  hl("@property", { fg = p.purple })
  hl("@attribute", { fg = p.purple })
  hl("@punctuation", { fg = p.fg_dark })
  hl("@string.escape", { fg = p.purple })
  hl("@string.special", { fg = p.purple })
  hl("@character", { fg = p.pink3 })
  hl("@tag", { fg = p.pink4 })
  hl("@tag.attribute", { fg = p.purple })
  hl("@tag.delimiter", { fg = p.fg_dark })
  hl("@markup.heading", { fg = p.yellow, bold = true })
  hl("@markup.strong", { bold = true })
  hl("@markup.italic", { italic = true })
  hl("@markup.strikethrough", { strikethrough = true })
  hl("@markup.link", { fg = p.purple, underline = true })
  hl("@markup.raw", { fg = p.pink3 })
  hl("@diff.plus", { fg = p.green })
  hl("@diff.minus", { fg = p.red })
  hl("@diff.delta", { fg = p.orange })

  -- Diagnostics
  hl("DiagnosticError", { fg = p.red })
  hl("DiagnosticWarn", { fg = p.yellow })
  hl("DiagnosticInfo", { fg = p.purple })
  hl("DiagnosticHint", { fg = p.green })
  hl("DiagnosticOk", { fg = p.green })
  hl("DiagnosticSignError", { fg = p.red })
  hl("DiagnosticSignWarn", { fg = p.yellow })
  hl("DiagnosticSignInfo", { fg = p.purple })
  hl("DiagnosticSignHint", { fg = p.green })
  hl("DiagnosticVirtualTextError", { fg = p.red })
  hl("DiagnosticVirtualTextWarn", { fg = p.yellow })
  hl("DiagnosticVirtualTextInfo", { fg = p.purple })
  hl("DiagnosticVirtualTextHint", { fg = p.green })
  hl("DiagnosticFloatingError", { fg = p.red })
  hl("DiagnosticFloatingWarn", { fg = p.yellow })
  hl("DiagnosticFloatingInfo", { fg = p.purple })
  hl("DiagnosticFloatingHint", { fg = p.green })
  hl("DiagnosticUnderlineError", { sp = p.red, undercurl = true })
  hl("DiagnosticUnderlineWarn", { sp = p.yellow, undercurl = true })
  hl("DiagnosticUnderlineInfo", { sp = p.purple, undercurl = true })
  hl("DiagnosticUnderlineHint", { sp = p.green, undercurl = true })
  hl("DiagnosticUnderlineOk", { sp = p.green, undercurl = true })
  hl("DiagnosticDeprecated", { sp = p.comment, strikethrough = true })
  hl("SpellBad", { sp = p.red, undercurl = true })
  hl("SpellCap", { sp = p.yellow, undercurl = true })
  hl("SpellRare", { sp = p.purple, undercurl = true })
  hl("SpellLocal", { sp = p.green, undercurl = true })

  -- Diff
  hl("DiffAdd", { fg = p.green, bg = bg_dark })
  hl("DiffDelete", { fg = p.red, bg = bg_dark })
  hl("DiffChange", { fg = p.orange, bg = bg_dark })
  hl("DiffText", { fg = p.fg, bg = p.selection_strong, bold = true })
  link("Added", "DiffAdd")
  link("Removed", "DiffDelete")
  link("Changed", "DiffChange")

  -- Pmenu
  hl("Pmenu", { fg = p.fg, bg = bg_dark })
  hl("PmenuSel", { fg = p.fg, bg = p.selection_strong })
  hl("PmenuSbar", { bg = bg_dark })
  hl("PmenuThumb", { bg = p.pink2 })
  hl("PmenuKind", { fg = p.purple, bg = bg_dark })
  hl("PmenuKindSel", { fg = p.fg_dark, bg = p.selection_strong })
  hl("PmenuExtra", { fg = p.muted, bg = bg_dark })
  hl("PmenuExtraSel", { fg = p.fg_dark, bg = p.selection_strong })
  hl("PmenuMatch", { fg = p.yellow, bg = bg_dark, bold = true })
  hl("PmenuMatchSel", { fg = p.yellow, bg = p.selection_strong, bold = true })

  -- LSP
  hl("LspReferenceText", { bg = p.selection })
  hl("LspReferenceRead", { bg = p.selection })
  hl("LspReferenceWrite", { bg = p.selection_strong })

  -- Snacks
  hl("SnacksPicker", { fg = p.fg, bg = bg })
  hl("SnacksPickerBorder", { fg = p.pink2, bg = bg })
  hl("SnacksPickerTitle", { fg = p.bg, bg = p.pink2, bold = true })
  hl("SnacksPickerInputBorder", { fg = p.pink2, bg = bg })
  hl("SnacksPickerInputTitle", { fg = p.bg, bg = p.pink2, bold = true })
  hl("SnacksPickerMatch", { fg = p.yellow, bold = true })
  hl("SnacksPickerFile", { fg = p.fg })
  hl("SnacksPickerDirectory", { fg = p.pink3, bold = true })
  hl("SnacksPickerDir", { fg = p.pink3, bold = true })
  hl("SnacksPickerIcon", { fg = p.pink2 })
  hl("SnacksPickerIconFile", { fg = p.pink3 })
  hl("SnacksPickerIconDirectory", { fg = p.pink2 })
  hl("SnacksPickerIconFolder", { fg = p.pink2 })
  hl("SnacksPickerTree", { fg = p.comment })
  hl("SnacksPickerSelected", { fg = p.pink })

  -- blink.cmp
  hl("BlinkCmpMenu", { fg = p.fg, bg = bg_dark })
  hl("BlinkCmpMenuBorder", { fg = p.pink2, bg = bg_dark })
  hl("BlinkCmpMenuSelection", { fg = p.fg, bg = p.selection_strong })
  hl("BlinkCmpLabelMatch", { fg = p.yellow, bold = true })
  hl("BlinkCmpDoc", { fg = p.fg, bg = bg_float })
  hl("BlinkCmpDocBorder", { fg = p.pink2, bg = bg_float })

  -- noice.nvim
  hl("NoiceCmdline", { fg = p.fg, bg = bg })
  hl("NoiceCmdlineIcon", { fg = p.purple })
  link("NoiceCmdlineIconCalculator", "NoiceCmdlineIcon")
  link("NoiceCmdlineIconCmdline", "NoiceCmdlineIcon")
  link("NoiceCmdlineIconFilter", "NoiceCmdlineIcon")
  link("NoiceCmdlineIconHelp", "NoiceCmdlineIcon")
  link("NoiceCmdlineIconIncRename", "NoiceCmdlineIcon")
  link("NoiceCmdlineIconInput", "NoiceCmdlineIcon")
  link("NoiceCmdlineIconLua", "NoiceCmdlineIcon")
  hl("NoiceCmdlineIconSearch", { fg = p.yellow })
  hl("NoiceCmdlinePopup", { fg = p.fg, bg = bg_float })
  hl("NoiceCmdlinePopupBorder", { fg = p.pink2, bg = bg_float })
  link("NoiceCmdlinePopupBorderCalculator", "NoiceCmdlinePopupBorder")
  link("NoiceCmdlinePopupBorderCmdline", "NoiceCmdlinePopupBorder")
  link("NoiceCmdlinePopupBorderFilter", "NoiceCmdlinePopupBorder")
  link("NoiceCmdlinePopupBorderHelp", "NoiceCmdlinePopupBorder")
  link("NoiceCmdlinePopupBorderIncRename", "NoiceCmdlinePopupBorder")
  link("NoiceCmdlinePopupBorderInput", "NoiceCmdlinePopupBorder")
  link("NoiceCmdlinePopupBorderLua", "NoiceCmdlinePopupBorder")
  hl("NoiceCmdlinePopupBorderSearch", { fg = p.yellow, bg = bg_float })
  hl("NoiceCmdlinePopupTitle", { fg = p.pink3, bg = bg_float, bold = true })
  hl("NoiceCmdlinePrompt", { fg = p.pink3, bold = true })

  hl("NoiceCompletionItemKindDefault", { fg = p.purple })
  hl("NoiceCompletionItemKindClass", { fg = p.pink4 })
  hl("NoiceCompletionItemKindColor", { fg = p.pink3 })
  hl("NoiceCompletionItemKindConstant", { fg = p.pink3 })
  hl("NoiceCompletionItemKindConstructor", { fg = p.purple })
  hl("NoiceCompletionItemKindEnum", { fg = p.pink4 })
  hl("NoiceCompletionItemKindEnumMember", { fg = p.purple })
  hl("NoiceCompletionItemKindField", { fg = p.purple })
  hl("NoiceCompletionItemKindFile", { fg = p.pink3 })
  hl("NoiceCompletionItemKindFolder", { fg = p.pink3 })
  hl("NoiceCompletionItemKindFunction", { fg = p.yellow })
  hl("NoiceCompletionItemKindInterface", { fg = p.pink4 })
  hl("NoiceCompletionItemKindKeyword", { fg = p.pink4 })
  hl("NoiceCompletionItemKindMethod", { fg = p.yellow })
  hl("NoiceCompletionItemKindModule", { fg = p.pink4 })
  hl("NoiceCompletionItemKindProperty", { fg = p.purple })
  hl("NoiceCompletionItemKindSnippet", { fg = p.orange })
  hl("NoiceCompletionItemKindStruct", { fg = p.pink4 })
  hl("NoiceCompletionItemKindText", { fg = p.fg })
  hl("NoiceCompletionItemKindUnit", { fg = p.pink3 })
  hl("NoiceCompletionItemKindValue", { fg = p.pink3 })
  hl("NoiceCompletionItemKindVariable", { fg = p.fg })
  hl("NoiceCompletionItemMenu", { fg = p.muted })
  hl("NoiceCompletionItemWord", { fg = p.fg })

  hl("NoiceConfirm", { fg = p.fg, bg = bg_float })
  hl("NoiceConfirmBorder", { fg = p.pink2, bg = bg_float })
  link("NoiceCursor", "Cursor")
  hl("NoiceFormatConfirm", { fg = p.fg, bg = p.selection })
  hl("NoiceFormatConfirmDefault", { fg = p.fg, bg = p.selection_strong })
  hl("NoiceFormatDate", { fg = p.pink3 })
  hl("NoiceFormatEvent", { fg = p.comment })
  hl("NoiceFormatKind", { fg = p.comment })
  hl("NoiceFormatLevelDebug", { fg = p.comment })
  hl("NoiceFormatLevelError", { fg = p.red })
  hl("NoiceFormatLevelInfo", { fg = p.purple })
  hl("NoiceFormatLevelOff", { fg = p.comment })
  hl("NoiceFormatLevelTrace", { fg = p.comment })
  hl("NoiceFormatLevelWarn", { fg = p.yellow })
  hl("NoiceFormatProgressDone", { fg = p.bg, bg = p.pink2 })
  hl("NoiceFormatProgressTodo", { fg = p.comment, bg = p.selection })
  hl("NoiceFormatTitle", { fg = p.pink3, bold = true })

  hl("NoiceLspProgressClient", { fg = p.pink3, bold = true })
  hl("NoiceLspProgressSpinner", { fg = p.yellow })
  hl("NoiceLspProgressTitle", { fg = p.comment })
  hl("NoiceMini", { fg = p.fg, bg = bg })
  hl("NoicePopup", { fg = p.fg, bg = bg_float })
  hl("NoicePopupBorder", { fg = p.pink2, bg = bg_float })
  hl("NoicePopupmenu", { fg = p.fg, bg = bg_dark })
  hl("NoicePopupmenuBorder", { fg = p.pink2, bg = bg_dark })
  hl("NoicePopupmenuMatch", { fg = p.yellow, bold = true })
  hl("NoicePopupmenuSelected", { fg = p.fg, bg = p.selection_strong })
  hl("NoiceScrollbar", { bg = bg_dark })
  hl("NoiceScrollbarThumb", { bg = p.pink2 })
  hl("NoiceSplit", { fg = p.fg, bg = bg_float })
  hl("NoiceSplitBorder", { fg = p.pink2, bg = bg_float })
  hl("NoiceVirtualText", { fg = p.purple })

  -- lazy.nvim
  hl("LazyNormal", { fg = p.fg, bg = bg_float })
  hl("LazyButton", { fg = p.fg, bg = p.selection })
  hl("LazyButtonActive", { fg = p.bg, bg = p.pink2, bold = true })
  hl("LazyH1", { fg = p.bg, bg = p.pink2, bold = true })
  hl("LazyH2", { fg = p.yellow, bold = true })

  hl("LazyComment", { fg = p.comment })
  hl("LazyDimmed", { fg = p.comment })
  hl("LazyBold", { fg = p.fg, bold = true })
  hl("LazyItalic", { fg = p.fg, italic = true })

  hl("LazyDir", { fg = p.pink3 })
  hl("LazyUrl", { fg = p.pink3, underline = true })
  hl("LazySpecial", { fg = p.purple })
  hl("LazyValue", { fg = p.pink3 })
  hl("LazyProp", { fg = p.comment })
  hl("LazyLocal", { fg = p.orange })
  hl("LazyCommit", { fg = p.purple })
  hl("LazyCommitIssue", { fg = p.orange })
  hl("LazyCommitType", { fg = p.pink4 })
  hl("LazyCommitScope", { fg = p.purple, italic = true })

  hl("LazyProgressDone", { fg = p.pink2 })
  hl("LazyProgressTodo", { fg = p.comment })

  hl("LazyReasonCmd", { fg = p.pink4 })
  hl("LazyReasonEvent", { fg = p.orange })
  hl("LazyReasonFt", { fg = p.pink3 })
  hl("LazyReasonImport", { fg = p.fg })
  hl("LazyReasonKeys", { fg = p.yellow })
  hl("LazyReasonPlugin", { fg = p.purple })
  hl("LazyReasonRequire", { fg = p.yellow })
  hl("LazyReasonRuntime", { fg = p.purple })
  hl("LazyReasonSource", { fg = p.pink3 })
  hl("LazyReasonStart", { fg = p.pink2 })

  hl("LazyError", { fg = p.red })
  hl("LazyWarning", { fg = p.yellow })
  hl("LazyInfo", { fg = p.purple })
  hl("LazyTaskOutput", { fg = p.comment })


  -- mason.nvim / :Mason
  hl("MasonNormal", { fg = p.fg, bg = bg_float })

  hl("MasonHeader", { fg = p.bg, bg = p.pink2, bold = true })
  hl("MasonHeaderSecondary", { fg = p.bg, bg = p.purple, bold = true })

  hl("MasonHighlight", { fg = p.pink3 })
  hl("MasonHighlightSecondary", { fg = p.purple })

  hl("MasonHighlightBlock", { fg = p.bg, bg = p.pink2 })
  hl("MasonHighlightBlockBold", { fg = p.bg, bg = p.pink2, bold = true })
  hl("MasonHighlightBlockSecondary", { fg = p.bg, bg = p.purple })
  hl("MasonHighlightBlockBoldSecondary", { fg = p.bg, bg = p.purple, bold = true })

  hl("MasonMuted", { fg = p.comment })
  hl("MasonMutedBlock", { fg = p.bg_dark, bg = p.muted})
  hl("MasonMutedBlockBold", { fg = p.bg, bg = p.comment, bold = true })


  -- gitsigns.nvim
  hl("GitSignsAdd", { fg = p.green })
  hl("GitSignsChange", { fg = p.yellow })
  hl("GitSignsDelete", { fg = p.red })

  hl("GitSignsTopdelete", { fg = p.red })
  hl("GitSignsChangedelete", { fg = p.orange })
  hl("GitSignsUntracked", { fg = p.green })

  hl("GitSignsAddNr", { fg = p.green })
  hl("GitSignsChangeNr", { fg = p.yellow })
  hl("GitSignsDeleteNr", { fg = p.red })

  hl("GitSignsAddLn", { bg = "#2f453d" })
  hl("GitSignsChangeLn", { bg = "#4a3f42" })
  hl("GitSignsDeleteLn", { bg = "#4a3040" })

  hl("GitSignsAddInline", { bg = "#2f453d" })
  hl("GitSignsChangeInline", { bg = "#4a3f42" })
  hl("GitSignsDeleteInline", { bg = "#4a3040" })

  hl("GitSignsCurrentLineBlame", { fg = p.comment, italic = true })


  -- which-key.nvim
  hl("WhichKeyNormal", { fg = p.fg, bg = bg_float })
  hl("WhichKeyBorder", { fg = p.pink2, bg = bg_float })
  hl("WhichKeyTitle", { fg = p.bg, bg = p.pink2, bold = true })

  hl("WhichKey", { fg = p.pink3, bold = true })
  hl("WhichKeyGroup", { fg = p.pink4, bold = true })
  hl("WhichKeyDesc", { fg = p.fg })
  hl("WhichKeySeparator", { fg = p.comment })
  hl("WhichKeyValue", { fg = p.comment })

  hl("WhichKeyIcon", { fg = p.pink3 })
  hl("WhichKeyIconAzure", { fg = p.purple })
  hl("WhichKeyIconBlue", { fg = p.purple })
  hl("WhichKeyIconCyan", { fg = p.pink3 })
  hl("WhichKeyIconGreen", { fg = p.green })
  hl("WhichKeyIconGrey", { fg = p.comment })
  hl("WhichKeyIconOrange", { fg = p.orange })
  hl("WhichKeyIconPurple", { fg = p.purple })
  hl("WhichKeyIconRed", { fg = p.red })
  hl("WhichKeyIconYellow", { fg = p.yellow })



end

return M
